#!/bin/bash
cd /home/pi/talk
./connectblue
for f in sayings/*.txt
do
/usr/local/bin/gtts-cli -f $f -o ./next.mp3
rm final.mp3
rm next_s.mp3
ffmpeg -i next.mp3 -ac 2 next_s.mp3
sox chime_use.mp3 next_s.mp3 final.mp3
play -v 1.5 final.mp3
rm $f
done


	
